export   const data = [
    {
        id:1,
        name:'Eugene',
        age:'27',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1595959131/person-2_ipcjws.jpg',
    },
    {
        id:2,
        name:'Alta',
        age:'26',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1595959131/person-3_rxtqvi.jpg',
    },
    {
        id:3,
        name:'Ricardo',
        age:'26',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883423/person-4_t9nxjt.jpg',
    },
    {
        id:4,
        name:'Alexander',
        age:'23',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883417/person-3_ipa0mj.jpg',
    },
    {
        id:5,
        name:'Blake',
        age:'29',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883334/person-1_rfzshl.jpg',
    },
    {
        id:6,
        name:'Saad',
        age:'29',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883417/person-3_ipa0mj.jpg',
    },
    {
        id:7,
        name:'Mahad',
        age:'25',
        image:'https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883417/person-3_ipa0mj.jpg',

    },
]